apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: cloud-app
type: Opaque
stringData:
  db-user: cloudapp
  db-password: cloudapp

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: cloud-app
data:
  DB_URL: "jdbc:postgresql://postgres:5432/cloudapp"