#!/bin/bash
# Seed script — posts 100 quotes to the API.
# Usage:
#   ./scripts/seed.sh                          # uses localhost:8080
#   ./scripts/seed.sh http://34.9.233.219      # uses GKE external IP

set -euo pipefail

BASE_URL="${1:-http://localhost:8080}"

post_quote() {
  local text="$1"
  local author="$2"
  curl -sf -X POST "$BASE_URL/quotes" \
    -H "Content-Type: application/json" \
    -d "{\"text\": \"$text\", \"author\": \"$author\"}" > /dev/null
  echo "  ✓ $author"
}

echo "Seeding 100 quotes to $BASE_URL..."
echo ""

post_quote "Talk is cheap. Show me the code." "Linus Torvalds"
post_quote "Any fool can write code that a computer can understand. Good programmers write code that humans can understand." "Martin Fowler"
post_quote "First, solve the problem. Then, write the code." "John Johnson"
post_quote "Experience is the name everyone gives to their mistakes." "Oscar Wilde"
post_quote "In order to be irreplaceable, one must always be different." "Coco Chanel"
post_quote "Java is to JavaScript what car is to Carpet." "Chris Heilmann"
post_quote "Knowledge is power." "Francis Bacon"
post_quote "Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code." "Dan Salomon"
post_quote "Perfection is achieved not when there is nothing more to add, but rather when there is nothing more to take away." "Antoine de Saint-Exupery"
post_quote "Code is like humor. When you have to explain it, it is bad." "Cory House"
post_quote "Fix the cause, not the symptom." "Steve Maguire"
post_quote "Optimism is an occupational hazard of programming; feedback is the treatment." "Kent Beck"
post_quote "When to use iterative development? You should use iterative development only on projects that you want to succeed." "Martin Fowler"
post_quote "Simplicity is the soul of efficiency." "Austin Freeman"
post_quote "Before software can be reusable it first has to be usable." "Ralph Johnson"
post_quote "Make it work, make it right, make it fast." "Kent Beck"
post_quote "The best way to get a project done faster is to start sooner." "Jim Highsmith"
post_quote "The most important property of a program is whether it accomplishes the intention of its user." "C.A.R. Hoare"
post_quote "A language that does not affect the way you think about programming is not worth knowing." "Alan Perlis"
post_quote "Programs must be written for people to read, and only incidentally for machines to execute." "Harold Abelson"
post_quote "The function of good software is to make the complex appear to be simple." "Grady Booch"
post_quote "Without requirements or design, programming is the art of adding bugs to an empty text file." "Louis Srygley"
post_quote "Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it." "Brian Kernighan"
post_quote "The most disastrous thing that you can ever learn is your first programming language." "Alan Kay"
post_quote "The computer was born to solve problems that did not exist before." "Bill Gates"
post_quote "There are only two kinds of languages: the ones people complain about and the ones nobody uses." "Bjarne Stroustrup"
post_quote "It is not enough for code to work." "Robert C. Martin"
post_quote "One of my most productive days was throwing away 1000 lines of code." "Ken Thompson"
post_quote "The best error message is the one that never shows up." "Thomas Fuchs"
post_quote "Every great developer you know got there by solving problems they were unqualified to solve until they did it." "Patrick McKenzie"
post_quote "It always seems impossible until it is done." "Nelson Mandela"
post_quote "In the middle of every difficulty lies opportunity." "Albert Einstein"
post_quote "The only way to do great work is to love what you do." "Steve Jobs"
post_quote "Innovation distinguishes between a leader and a follower." "Steve Jobs"
post_quote "Your time is limited, so do not waste it living someone else's life." "Steve Jobs"
post_quote "Stay hungry, stay foolish." "Steve Jobs"
post_quote "Design is not just what it looks like and feels like. Design is how it works." "Steve Jobs"
post_quote "The people who are crazy enough to think they can change the world are the ones who do." "Steve Jobs"
post_quote "We cannot solve our problems with the same thinking we used when we created them." "Albert Einstein"
post_quote "Imagination is more important than knowledge." "Albert Einstein"
post_quote "Life is like riding a bicycle. To keep your balance, you must keep moving." "Albert Einstein"
post_quote "The measure of intelligence is the ability to change." "Albert Einstein"
post_quote "Try not to become a man of success, but rather try to become a man of value." "Albert Einstein"
post_quote "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change." "Charles Darwin"
post_quote "The secret of getting ahead is getting started." "Mark Twain"
post_quote "The best time to plant a tree was 20 years ago. The second best time is now." "Chinese Proverb"
post_quote "An investment in knowledge pays the best interest." "Benjamin Franklin"
post_quote "Tell me and I forget. Teach me and I remember. Involve me and I learn." "Benjamin Franklin"
post_quote "By failing to prepare, you are preparing to fail." "Benjamin Franklin"
post_quote "Well done is better than well said." "Benjamin Franklin"
post_quote "You miss 100 percent of the shots you never take." "Wayne Gretzky"
post_quote "Whether you think you can or you think you cannot, you are right." "Henry Ford"
post_quote "The only limit to our realization of tomorrow will be our doubts of today." "Franklin D. Roosevelt"
post_quote "Do not watch the clock. Do what it does. Keep going." "Sam Levenson"
post_quote "Success is not final, failure is not fatal: it is the courage to continue that counts." "Winston Churchill"
post_quote "We are what we repeatedly do. Excellence, then, is not an act, but a habit." "Aristotle"
post_quote "The unexamined life is not worth living." "Socrates"
post_quote "I think, therefore I am." "Rene Descartes"
post_quote "The only true wisdom is in knowing you know nothing." "Socrates"
post_quote "He who has a why to live can bear almost any how." "Friedrich Nietzsche"
post_quote "That which does not kill us makes us stronger." "Friedrich Nietzsche"
post_quote "Without music, life would be a mistake." "Friedrich Nietzsche"
post_quote "In the beginning was the Word, and the Word was with God, and the Word was God." "Bible"
post_quote "To be or not to be, that is the question." "William Shakespeare"
post_quote "All the world's a stage, and all the men and women merely players." "William Shakespeare"
post_quote "Good night, good night! Parting is such sweet sorrow." "William Shakespeare"
post_quote "We know what we are, but know not what we may be." "William Shakespeare"
post_quote "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife." "Jane Austen"
post_quote "I am not afraid of storms, for I am learning how to sail my ship." "Louisa May Alcott"
post_quote "It does not do to dwell on dreams and forget to live." "J.K. Rowling"
post_quote "It is our choices that show what we truly are, far more than our abilities." "J.K. Rowling"
post_quote "Not all those who wander are lost." "J.R.R. Tolkien"
post_quote "Even the smallest person can change the course of the future." "J.R.R. Tolkien"
post_quote "There is some good in this world, and it is worth fighting for." "J.R.R. Tolkien"
post_quote "The truth is rarely pure and never simple." "Oscar Wilde"
post_quote "Be yourself; everyone else is already taken." "Oscar Wilde"
post_quote "Always forgive your enemies; nothing annoys them so much." "Oscar Wilde"
post_quote "I can resist everything except temptation." "Oscar Wilde"
post_quote "Two things are infinite: the universe and human stupidity; and I am not sure about the universe." "Albert Einstein"
post_quote "I have not failed. I have just found 10,000 ways that do not work." "Thomas Edison"
post_quote "Genius is one percent inspiration and ninety-nine percent perspiration." "Thomas Edison"
post_quote "The way to get started is to quit talking and begin doing." "Walt Disney"
post_quote "All our dreams can come true, if we have the courage to pursue them." "Walt Disney"
post_quote "It is kind of fun to do the impossible." "Walt Disney"
post_quote "You can observe a lot just by watching." "Yogi Berra"
post_quote "In theory, theory and practice are the same. In practice, they are not." "Yogi Berra"
post_quote "Give me six hours to chop down a tree and I will spend the first four sharpening the axe." "Abraham Lincoln"
post_quote "Whatever you are, be a good one." "Abraham Lincoln"
post_quote "In the end, it is not the years in your life that count. It is the life in your years." "Abraham Lincoln"
post_quote "Float like a butterfly, sting like a bee." "Muhammad Ali"
post_quote "I hated every minute of training, but I said do not quit. Suffer now and live the rest of your life as a champion." "Muhammad Ali"
post_quote "If my mind can conceive it, and my heart can believe it, then I can achieve it." "Muhammad Ali"
post_quote "The future belongs to those who believe in the beauty of their dreams." "Eleanor Roosevelt"
post_quote "Do one thing every day that scares you." "Eleanor Roosevelt"
post_quote "No one can make you feel inferior without your consent." "Eleanor Roosevelt"
post_quote "It is better to fail in originality than to succeed in imitation." "Herman Melville"
post_quote "We must accept finite disappointment, but never lose infinite hope." "Martin Luther King Jr."
post_quote "Darkness cannot drive out darkness; only light can do that." "Martin Luther King Jr."

echo ""
echo "Done! 100 quotes seeded to $BASE_URL"
echo ""
echo "Verify:"
echo "  curl $BASE_URL/quotes/stats"